### ISSUE TITLE
Fix autocommit

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scverse-tutorials#125]
[the last workflow run](https://github.com/scverse/scverse-tutorials/actions/runs/7022024836/job/19105444669?pr=124) exited with

```
Run stefanzweifel/git-auto-commit-action@v4
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
INPUT_REPOSITORY value: .
INPUT_STATUS_OPTIONS: 
INPUT_FILE_PATTERN: .
INPUT_BRANCH value: template-update-scverse-scverse-tutorials-v0.3.0
From https://github.com/scverse-bot/scverse-tutorials
 * [new branch]      anndata-mudata-getting-started-beginners -> origin/anndata-mudata-getting-started-beginners
 * [new branch]      main       -> origin/main
 * [new branch]      template-update-jlause-scverse-tutorials-v0.2.21 -> origin/template-update-jlause-scverse-tutorials-v0.2.21
 * [new branch]      template-update-jlause-scverse-tutorials-v0.2.22 -> origin/template-update-jlause-scverse-tutorials-v0.2.22
 * [new branch]      template-update-jlause-scverse-tutorials-v0.3.0 -> origin/template-update-jlause-scverse-tutorials-v0.3.0
 * [new branch]      template-update-scverse-scverse-tutorials-v0.2.21 -> origin/template-update-scverse-scverse-tutorials-v0.2.21
 * [new branch]      template-update-scverse-scverse-tutorials-v0.2.22 -> origin/template-update-scverse-scverse-tutorials-v0.2.22
Already on 'template-update-scverse-scverse-tutorials-v0.3.0'
M	docs/notebooks/anndata_getting_started.ipynb
M	docs/notebooks/basic-scrna-tutorial.ipynb
M	docs/notebooks/scverse_data_backed.ipynb
M	docs/notebooks/tutorial_axes_anndata_mudata.ipynb
M	docs/notebooks/tutorial_concatenation_anndata_mudata.ipynb
Your branch is up to date with 'origin/template-update-scverse-scverse-tutorials-v0.3.0'.
INPUT_ADD_OPTIONS: 
INPUT_FILE_PATTERN: .
INPUT_COMMIT_OPTIONS: 
INPUT_COMMIT_USER_NAME: github-actions[bot]
INPUT_COMMIT_USER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
INPUT_COMMIT_MESSAGE: Render notebooks
INPUT_COMMIT_AUTHOR: flying-sheep <flying-sheep@users.noreply.github.com>
[template-update-scverse-scverse-tutorials-v0.3.0 ed81a2f] Render notebooks
 Author: flying-sheep <flying-sheep@users.noreply.github.com>
 5 files changed, 730 insertions(+), 404 deletions(-)
INPUT_TAGGING_MESSAGE: 
No tagging message supplied. No tag will be added.
INPUT_PUSH_OPTIONS: 
remote: Permission to scverse-bot/scverse-tutorials.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/scverse-bot/scverse-tutorials/': The requested URL returned error: 403
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

**Comment by grst** [comment]
yeah this is actually a problem... The "render notebook" CI doesn't work on forks due to permission issues.
